[package]
name = "HandwrittenClassifier"
version = "0.1.0"
edition = "2024"

[dependencies]
tch = "0.13"       # PyTorch bindings
image = "0.24"     # Image processing
clap = { version = "4.0", features = ["derive"] } # CLI parsing
anyhow = "1.0"     # Error handling